# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8811e4f0e8d783a62d8205bfd9622646b55a16a5f09a224a0093ec45e490aa37a628d87074333ae389b352772603611ef7a2c2d411429444a41b9be1b3d8caa

test:
  secret_key_base: cca7e675f0cc890c0eb9ccd26a72eed540cebc2fbff03e3f8da0ada32197c0caabff33e1a45c2207c035a3bea81d14572894f2629217fb52d7681ab4d18d44d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
